version: '3'

services:

  setprotocol-subgraph:
    image: ${SET_IMAGE_NAME}:node-${NODE_VER}
    environment:
      DEPLOYMENT: ${DEPLOYMENT:-local}
      IPFS_IP: ${IPFS_IP:-""}
      GRAPH_NODE_IP: ${GRAPH_NODE_IP:-""}
      ACCESS_TOKEN: ${ACCESS_TOKEN:-test}
      SUBGRAPH_VERSION: ${SUBGRAPH_VERSION:-""}
      NETWORK_NAME: ${NETWORK_NAME:-hardhat}
      GITHUB_REPO: ${GITHUB_REPO:-SetProtocol}
      SUBGRAPH_NAME: ${SUBGRAPH_NAME}
    volumes:
      - ../:/subgraph
      - setprotocol-subgraph-node_modules:/subgraph/node_modules
    working_dir: /subgraph
    command: ["sh", "./scripts/deploy.sh"]

volumes:
  setprotocol-subgraph-node_modules:
    external: false
