version: '3'

services:

  hardhat-build:
    image: ${SET_IMAGE_NAME}:node-${NODE_VER}
    environment:
      HARDHAT_PORT: ${HARDHAT_PORT:-"8545"}
      REPO_URL: ${REPO_URL}
      REPO_BRANCH_OR_TAG: ${REPO_BRANCH_OR_TAG:-master}
      TEST_SCRIPT: ${TEST_SCRIPT}
    working_dir: /app
    volumes:
      - ../scripts:/app/scripts
      - hardhat:/app

volumes:
  hardhat:
    external: false
